### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by dklesev** [HunanTV/redis-ctl#14]
Nice project - useful UI.
But is it possible to add english language?
With google translate its usable bu ugly.

**Comment by neuront** [comment]
Sure. Since some of the content is dynamically loaded, I think it's a good idea to change it by JS. Maybe we could use [jquery-localize](https://github.com/coderifous/jquery-localize)

**Comment by zheplusplus** [comment]
@dklesev hi, there. We've localized most content in the index page, Redis panel pages and cluster panel pages after #15 merged. Most of the work are done in front-end by jquery-localize.

There is still much work left, and we think that we need a more natural way to deal with the translations. 

So tell us if you need any help, or get any better ideas. Either issues or pull requests are welcome!

**Comment by dklesev** [comment]
@neuront ok, thank you, will look at it when I find time.

**Comment by zheplusplus** [comment]
We have changed the UI text in English as the default, and provided Chinese as a translation patch after 0.9.1 merged.
