### ISSUE TITLE
about db structure upgrade

### ISSUE THREAD

**Issue by jasonjoo2010** [HunanTV/redis-ctl#19]
We use create_all to create all tables we need currently.

but it will not alter them when we make some changes on them.

Is it necessary to make a db-version module replacing the create_all?

regards,

**Comment by zheplusplus** [comment]
I suppose a less painful practice is to use [sqlalchemy-migration](https://sqlalchemy-migrate.readthedocs.io/en/latest/). But I'm not quite familiar with it yet :(

**Comment by jasonjoo2010** [comment]
yeah, it's a solution. I try to figure it out
