### ISSUE TITLE
redis-trib version

### ISSUE THREAD

**Issue by jasonjoo2010** [HunanTV/redis-ctl#20]
we don't specify a version for redis-trib in requirements.txt but the new version (eg: 0.5.0) there is some changes for Talker. A new class connection replaces Talker.

Currently we use

> from redistrib.connection import Connection as Talker

to make it work again.

is it necessary to specify a version in requirements? and upgrade the code to use newest version?

**Comment by zheplusplus** [comment]
In the current requirements.txt `redis-trib==0.4.1` is specified as to avoid the problem.

And the fix is on the way :)

**Comment by zheplusplus** [comment]
Oops found a big mistake that I set the default branch to v0.9 but not the master. So that if you are using master the code will indeed break.

**Comment by jasonjoo2010** [comment]
yeah, not so serious problem, and only small changes should be made to upgrade to new version.

so shall we upgrade or stay 0.4?

**Comment by zheplusplus** [comment]
The updates using `redis-trib>=0.5` has been merged the branch v0.9.
