### ISSUE TITLE
可以支持一下docker版吗？

### ISSUE THREAD

**Issue by Odinysus** [HunanTV/redis-ctl#30]
或者说有没有这个计划

**Comment by CMGS** [comment]
支持 docker 的意思是？需要一个 image 镜像么

**Comment by Odinysus** [comment]
这个项目需要python，而且还需要编译。此项目打包成docker镜像，方便下载使用啊。

**Comment by CMGS** [comment]
呃…理论上来说我们不会提供一个 docker image （主要是受限于 registry 的维护），顶多顶多顶多提供一个 Dockerfile
对于此项目来说，通过 ```pip install``` 就能解决依赖安装问题了，自行写一个 Dockerfile 也不算难事
长期规划来讲，projecteru2 发布之后我们会对这个项目发布由 eru2 生成的 Dockerfile 的

**Comment by Odinysus** [comment]
我的系统是mac os 10.12 
在 pip install ./requirements.txt
安装python-mysql的时候，碰到大坑。至今没跑起来。我把应用部署在阿里云服务器centos 7.5时，
执行命令
```
pip install -r requirements.txt
```
出现下面这个错误（与mac上的错误类似）提示：
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b4RaPZ/MySQL-python/
```

**Comment by CMGS** [comment]
@johnMaster 你这个错误……是没找到 libmysqlclient.so 这个文件……实际上你应该看 pip 的完整日志输出，而不是 pip 最终输出。

**Comment by Odinysus** [comment]
成功了，是centos上面装有部分mysql的组件，将组件完全卸载之后重装就好了
